### PR TITLE
Fix bad while loop increment conversion in FractionPrinterParser

### PR DESCRIPTION
**Pull request by easel**

### CODE REVIEW

**Comment by soc** [comment]
Looking at the Java code, I think https://github.com/easel/threetenbp/blob/fraction-parser/src/main/scala/org/threeten/bp/format/DateTimeFormatterBuilder.scala#L589 needs the same fix:

https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/format/DateTimeFormatterBuilder.java#L2452
https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/format/DateTimeFormatterBuilder.java#L2749

 Could you add that one, too?

Thanks a lot!

**Comment by easel** [comment]
Good call. I did a search but didn't manage to find more cases, I figured they must be out there. Will update shortly.

**Comment by soc** [comment]
I really really hope this is something I messed up, and not a bug in the Java-to-Scala converter ...

**Comment by easel** [comment]
Yeah it really looked like a human error to me too but I had trouble finding a human to blame in the history. It's a really weird error to come from a code generator though!

**Comment by soc** [comment]
Ooops, sorry, I think the link I gave wasn't an instance of this issue. Sorry for the confusion. Local tests confirm that a ton of errors have been eliminated!

    - [info] Tests: succeeded 10895, failed 583, canceled 0, ignored 172, pending 0
    + [info] Tests: succeeded 11275, failed 203, canceled 0, ignored 172, pending 0

Thanks a lot!

**Pull request merged**
