### PR TITLE
Rename org.threeten.bp to java.time

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
@alonsodomin I'm seeing compilation failures with the Maven build after this change. It feels like it didn't pick up the `-Xexperimental` flag, although I didn't change anything there. Any ideas?

**Comment by alonsodomin** [comment]
Hi @soc, I took a brief look into it right now. The kind of compilation failures that I've seen in this `rename-2` branch are all in the test code and sort of like this one:

```
[ERROR] /Users/alonsodomin/Workspace/Projects/threetenbp/src/test/scala/java/time/FluentAPIChecker.scala:67: error: type mismatch;
[ERROR]  found   : () => java.time.temporal.TemporalAdjuster
[ERROR]  required: java.time.temporal.TemporalAdjuster
[ERROR]     date = date.`with`(lastDayOfMonth)
```

That kind of error is makes me think that the compiler is interpreting that, by passing `lastDayOfMonth` as a method reference instead of the actual result of it... a sort of error that I've seen before with methods that were defined with an empty parameter list and then used (invoked) without even the empty parens... I actually tried to put the empty parens to that `lastDayOfMonth` usage and saw how some of those errors went away.

However in the actual code `lastDayOfMonth` is defined without any parameters, not even the empty parens. Could it be that Maven is compiling the tests agains the actual JDK instead of the code? I don´t have a pre-JDK8 installed in my laptop so I couldn't try to compile in other versions yet so see if that is the actual problem.

In my case removing the `-Xexperimental` flag from the compiler didn't help, it in fact made it fail to compile the main code.

**Comment by alonsodomin** [comment]
btw @soc, do you have those SBT build files in some branch? It might be possible (or easier than with Maven) to make SBT compiling the code giving preferrence to the classes in the `main` folder over the ones in the JDK... Sort of similar that what the ScalaJS guys do...

**Comment by soc** [comment]
@alonsodomin I have the code at my workstation at home. I will push it later as soon as possible! Thanks!

**Comment by soc** [comment]
I'll close this until we know more! Thanks everyone!

**Pull request closed without merging**
