### PR TITLE
Adding Scala compiler and allowed loading of TZDATA

### PR DESCRIPTION
**Pull request by alonsodomin**
I'm aware that the purpose of the initial fork is not to arrive at pure scala implementation of the JSR-310, but I wanted to play with this code and at least make it compile and load the time zone data. Lots of tests are still failing though.

### CODE REVIEW

**Comment by soc** [comment]
@alonsodomin Hey Alonso! This is amazing! Thanks a lot for the contribution! (A pure Scala implementation is more or less the goal.¹) Not sure if keeping the POM files make sense, but it's better than before!
Translating so much code, and than having it failing almost immediately was quite frustrating for me, so thanks a lot for pushing through!

Are you happy with this PR to be merged? Could you, to be very explicit about it, state that you are the original creator of these changes, are allowed to contribute them, and agree to license your work under the license specified in https://github.com/soc/threetenbp/blob/master/LICENSE.txt?

¹ Although I need to think about the additional changes required which are necessary to reap the full benefits of a pure Scala implementation (Scala.js compatibility!).

**Comment by alonsodomin** [comment]
Hi @soc, yeah, I'm the original authour of the (minor) changes and happy to merge them under the original license.

I agree with you regarding the POM files, I rather replace them by SBT build files but I started with the POM to be able to quickly get a compilable and start running some of the tests. I noticed that I had to enable the experimental feature in scalac as the translated code makes quite a lot of usage of SAMs but so far, at least, it's possible to generate a JAR file.

As I said, many tests still fail but when going through them, some of them are due to using a direct translation of the Java switch statement into a Scala match (which fails in runtime if not exahustive) or even testing whether a class (e.g.: LocalTime) is immutable or not - which doesn't make too much sense in Scala when using a case class.

I could PR some additional changes for the previous soon (already pushed to my own fork), don't know how you would like it manage, whether as part of this PR or as a newer one. I would really welcome having a full working Scala impl that is available for Scala.js too and wouldn´t mind to give a hand in my free time.

**Comment by alonsodomin** [comment]
ups! just noticed that pushing those changes to my own fork make them available in this PR so nevermind.

**Comment by soc** [comment]
Looks great to me! Are you happy with merging it?

**Comment by alonsodomin** [comment]
Yep, you are right, the impl relies in null checks in a few places, I think that the most obvious one I could spot is the ```yearToGregorianEpochDay``` for that class:

```scala
private def yearToGregorianEpochDay(prolepticYear: Int): Long = {
    val cycleNumber: Int = (prolepticYear - 1) / 30
    val yearInCycle: Int = (prolepticYear - 1) % 30
    var dayInCycle: Int = getAdjustedCycle(cycleNumber)(Math.abs(yearInCycle)).intValue
    if (yearInCycle < 0) {
      dayInCycle = -dayInCycle
    }
    var cycleDays: java.lang.Long = null
    try {
      cycleDays = ADJUSTED_CYCLES(cycleNumber)
    }
    catch {
      case e: ArrayIndexOutOfBoundsException =>
        cycleDays = null
    }
    if (cycleDays == null) {
      cycleDays = new java.lang.Long(cycleNumber * 10631)
    }
    (cycleDays.longValue + dayInCycle + HIJRAH_JAN_1_1_GREGORIAN_DAY - 1)
  }
```

The potential *unnecessary null check* warning gets voided somehow due to the catch block assigning the ```null``` value to the ```cycleDays``` var. Think I got confused by the numerous places in which in querying a map instead of an array, like in the following:

```scala
private def getAdjustedCycle(cycleNumber: Int): Array[Int] = {
    var cycles: Array[Int] = null
    try {
      cycles = ADJUSTED_CYCLE_YEARS.get(cycleNumber)
    }
    catch {
      case e: ArrayIndexOutOfBoundsException => {
        cycles = null
      }
    }
    if (cycles == null) {
      cycles = DEFAULT_CYCLE_YEARS
    }
    cycles
  }
```

Most of that class needs to be re-implemented anyway so no prob on leaving that out.

**Comment by soc** [comment]
Ok, great! If it's not too much trouble, could you drop the commit instead of reverting it so that we have a clean history?

**Comment by alonsodomin** [comment]
ok, rewrote the history of the branch removing the offending commit and the revert one

**Comment by soc** [comment]
Thanks!

**Comment by soc** [comment]
@alonsodomin I was confused the whole time about 

> I agree with you regarding the POM files, I rather replace them by SBT build files but I started with the POM to be able to quickly get a compilable and start running some of the tests. I noticed that I had to enable the experimental feature in scalac as the translated code makes quite a lot of usage of SAMs but so far, at least, it's possible to generate a JAR file.

now I got it ... I never checked in my existing SBT config.

I really have to apologize for wasting your time here and figuring out scalac options ... if I had checked those files in, it would have been obvious. :-/

**Pull request merged**
